FROM ubuntu:latest

# Install NFS server
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y nfs-kernel-server && \
    rm -rf /var/lib/apt/lists/*

# Create an export directory
RUN mkdir -p /exports

# Add NFS exports configuration
COPY exports /etc/exports

# Expose the NFS ports
EXPOSE 2049/tcp 2049/udp

# Start NFS server
CMD ["sh", "-c", "echo '/usr/sbin/exportfs -ra' >> /etc/bash.bashrc && /usr/sbin/rpc.nfsd --foreground --no-udp"]

