FROM debian:bullseye-slim

# Install NFS server
RUN apt-get update && \
    apt-get install -y nfs-kernel-server && \
    rm -rf /var/lib/apt/lists/*

# Add NFS exports configuration
COPY exports /etc/exports

# Expose the NFS ports
EXPOSE 2049/tcp 2049/udp

# Start NFS server
CMD ["sh", "-c", "rpcbind && service nfs-kernel-server start && tail -f /dev/null"]
