version: '3'

services:
  nfs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NFS-Server
    privileged: true
    volumes:
      - ./data:/exports
    ports:
      - "2049:2049"
    restart: unless-stopped
