version: '3.0'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - esnet
    deploy:
      placement:
        constraints: [node.role==manager]
#        constraints: [node.labels.name==ram]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200  
    ports:
      - 5601:5601
#    networks:
#      - esnet
    depends_on:
      - node01
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    deploy:
      placement:
        constraints: [node.labels.name==ram]
#        constraints: [node.role==manager]

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    volumes:
      - /run/media/vaibhavg/Backup/DOC/Back/Containers/docker-swarm/kibana/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
#    networks:
#      - esnet
    depends_on:
      - node01
    deploy:
      placement:
        constraints: [node.role==manager]

volumes:
  es-data01:
    driver: local

#networks:
#  esnet:
