# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  #Docker Master Node
  config.vm.define "docker-master1" do |master|
    master.vm.hostname = "master"
    master.vm.box = "ubuntu/focal64"
    master.vm.network :private_network, ip: "192.168.56.103"

    # Provisioning script for updating and upgrading
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
      sudo hostnamectl set-hostname fedora.cn.lan
    SHELL
  end

  #Docker Node 1
  config.vm.define "docker-node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "ubuntu/focal64"
    node1.vm.network :private_network, ip: "192.168.56.101"

    # Provisioning script for updating and upgrading
    node1.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
    SHELL
  end

  #Docker Node 2
  config.vm.define "docker-node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.box = "ubuntu/focal64"
    node2.vm.network :private_network, ip: "192.168.56.102"

    # Provisioning script for updating and upgrading
    node2.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
  end
end

