version: '3.0'

services:
  node01:
    image: elasticsearch:8.12.0
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-8
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    environment:
      ELASTIC_HOSTS: http://node01:9200
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - node01

  heartbeat:
    image: elastic/heartbeat:8.12.0
    container_name: heartbeat
    environment:
      ELASTIC_HOSTS: http://node01:9200
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    networks:
      - es-network
    depends_on:
      - node01

volumes:
  es-data01:
    driver: local

networks:
  es-network:
    driver: bridge
