version: '3' 
services: 
        remote_host_one: 
                container_name: remote-host-one 
                image: remote-host-ssh 
                build: 
                        context: ./ 
                networks: 
                        - net 

        remote_host_two: 
                container_name: remote-host-two
                image: remote-host-ssh 
                build: 
                        context: ./ 
                networks: 
                        - net 
                
networks: 
        net: 

