version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    command: >
      sh -c "apt-get update && apt-get install -y net-tools vim screen &&
      curl https://get.docker.com/ > /var/jenkins_home/dockerinstall &&
      chmod 777 /var/jenkins_home/dockerinstall &&
      ./var/jenkins_home/dockerinstall &&
      chmod 666 /var/run/docker.sock &&
      /usr/local/bin/jenkins.sh"
    networks:
      - jenkins-net

  jenkins-node:
    image: ubuntu
    container_name: jenkins-node
    command: >
      sh -c "apt-get update && apt-get install -y net-tools vim screen && tail -f /dev/null"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /home/jenkins  # Mount the /home/jenkins directory
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_home:
