version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    command: >
      sh -c "apt-get update && apt-get install -y net-tools iputils-ping curl vim screen &&
      curl https://get.docker.com/ > /var/jenkins_home/dockerinstall &&
      chmod 777 /var/jenkins_home/dockerinstall &&
      ./var/jenkins_home/dockerinstall &&
      chmod 666 /var/run/docker.sock &&
      /usr/local/bin/jenkins.sh"
    networks:
      - jenkins-net
    hostname: jenkins
    extra_hosts:
      - "jenkins-node:172.19.0.1"  # Use the actual IP of jenkins-node container if changed

  jenkins-node:
    image: ubuntu
    container_name: jenkins-node
    command: >
      sh -c "apt-get update && apt-get install -y net-tools iputils-ping vim curl screen default-jre-headless && 
      echo 'curl -sO http://172.19.0.1:8080/jnlpJars/agent.jar' >> /home/jenkins/imp.sh &&
      echo 'java -jar agent.jar -jnlpUrl http://172.19.0.1:8080/computer/node1%2Dcontainer/jenkins-agent.jnlp -secret ee577b6ba0e10be2bdd45e70164d4dbd41449f3df89718485c99527b1335214b -workDir "/home/jenkins"' >> /home/jenkins/imp.sh &&
      chmod +x /home/jenkins/imp.sh &&
      tail -f /dev/null"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /home/jenkins  # Mount the /home/jenkins directory
    networks:
      - jenkins-net
    hostname: jenkins-node

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
