version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    command: >
      sh -c "curl https://get.docker.com/ > /var/jenkins_home/dockerinstall &&
      chmod 777 /var/jenkins_home/dockerinstall &&
      ./var/jenkins_home/dockerinstall &&
      chmod 666 /var/run/docker.sock &&
      /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:
