filebeat.inputs:
- type: filestream
  id: default-filestream
  enabled: true
  paths:
    - ingest_data/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD} 

output.logstash:
  hosts: http://logstash01:5044
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}