version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
    hostname: jenkins
    extra_hosts:
      - "jenkins-node:172.19.0.1"
    restart: always

  jenkins-node:
    build:
      context: ./node1
      dockerfile: Dockerfile
    container_name: jenkins-node
    command: >
      sh -c "echo 'curl -sO http://172.19.0.3:8080/jnlpJars/agent.jar' >> /home/jenkins/imp.sh &&
      echo 'java -jar agent.jar -url http://172.19.0.3:8080/ -secret 53cd6a62762d47646b57f194dbf2762049fb14d036ae681224df02d7ae637bc3 -name node1 -workDir "/home/jenkins"' >> /home/jenkins/imp.sh &&
      chmod +x /home/jenkins/imp.sh &&
      tail -f /dev/null"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-node1:/home/jenkins
    networks:
      - jenkins-net
    hostname: jenkins-node

networks:
  jenkins-net:
    driver: bridge
volumes:
  jenkins_home:
