version: '3'

services:
  jenkins1:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins1
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
