version: '3'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - Portainer:/data
    ports:
      - 8090:9000 
    restart: always

volumes:
  Portainer:
    driver: local

 
